### ISSUE TITLE
As a user I want to read a KV from Astral

### ISSUE THREAD

**Issue by suprjinx** [G-Research/astral#48]
Given a user with a JWT

When the user wants to retrieve a secret from Vault via Astral
the user calls GET against /astral/v1/secrets
and
we validate the supplied token against the policies in Vault (which we should have in memory already, see story https://github.com/G-Research/astral/issues/56)
Then 
we return a response to the user with the requested secret (abstracted view details see story https://github.com/G-Research/astral/issues/57)

**Comment by GeorgeJahad** [comment]
All that is left here is the work required for:  https://github.com/G-Research/astral/issues/56
