### ISSUE TITLE
SPIKE: find out what is provided in Vault logs and determine what we want to collect from them

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/astral#60]

**Comment by GeorgeJahad** [comment]
The bad news is that vault audit logs are intentionally unhelpful, in that much of the data is hashed and can't be retrieved, it can only be compared.

In other words, you have to know the contents in advance and have to hash those contents to see if they exist in the log.

After reviewing this with the Erick's, we decided to back away from using the audit logs at all.

The workaround is that all certificate writes will go through Astral.  That way we can track all certs created without looking at the logs.

For secrets read/write, astral will still write policies to allow direct user access from the vault cli.  This is much higher traffic than cert creation so the Ericks want to allow bypassing Astral if needed.

Cert creation is much lower traffic, so it is ok to host that entirely on Astral.

**Comment by GeorgeJahad** [comment]
Created the scaled down task here: #86 

closing
