### ISSUE TITLE
Investigate making app registry requests

### ISSUE THREAD

**Issue by GeorgeJahad** [G-Research/astral#61]
Mainly want to see what kind of permissions are required. 

Figure out exactly what auth is   required.

**Comment by GeorgeJahad** [comment]
I was able to generate an app registry jwt, and use it to make an http request of the app registry api from my devpod.  Details here:
https://confluence.uberit.net/display/ENG/Astral+Implementation+Details

**Comment by suprjinx** [comment]
Looks good to me
